name: Update Repo Info in README

on:
  push:
    tags:
      - '*'  # Trigger on any new tag push
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update repo info in README
        uses: ./.github/actions/update-repo-info
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Git user
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      - name: Commit and push changes
        run: |
          git add README.md
          git commit -m "chore: update repo info in README" || echo "No changes to commit"
          git push
